version: '2.3'

services:
  roign:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros:ign-melodic-gui
    container_name: ros-ign
    network_mode: "host"
    privileged: true
    tty: true
    working_dir: /root
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ~/share:/root/share:rw
    devices:
      - /dev/dri:/dev/dri
    command: bash -c "source /opt/ros/melodic/setup.bash; roscore"
